name: performance_timer
description: A timer and utils to count time spent on methods and calculations
version: 1.0.0
repository: https://github.com/

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  duration: ^3.0.13

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
