name: performance_timer
description: A timer and utils to count time spent on methods and calculations
version: 1.2.0
repository: https://github.com/nicobritos/performance-timer

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  duration: ^3.0.13
  meta: ^1.7.0
  fixnum: ^1.1.0
  http: any
  quiver: ^3.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
